### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by aujkis** [paulpflug/opened-files#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [opened-files](https://github.com/paulpflug/opened-files) package, v0.0.5
### Stack Trace

Uncaught TypeError: Cannot read property 'style' of null

```
At /Users/Austris/.atom/packages/opened-files/lib/opened-files-view.coffee:93

TypeError: Cannot read property 'style' of null
  at OpenedFilesView.module.exports.OpenedFilesView.toggle (/Users/Austris/.atom/packages/opened-files/lib/opened-files-view.coffee:93:16)
  at OpenedFilesView.toggle (/Users/Austris/.atom/packages/opened-files/lib/opened-files-view.coffee:1:1)
  at atom-workspace.disposables.add.atom.commands.add.opened-files:toggle (/Users/Austris/.atom/packages/opened-files/lib/opened-files.coffee:42:41)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -1:16.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.8.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:33.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:33.4.0 opened-files:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:06.7.0 command-palette:toggle (div.settings-view.pane-item)
     -0:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 opened-files:toggle (div.settings-view.pane-item)
```
### Config

``` json
{
  "core": {
    "destroyEmptyPanes": false
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
autocomplete-sass, v0.1.0
autohide-tree-view, v0.20.1
bookmarks, v0.35.0
chary-tree-view, v0.2.3
color-picker, v2.0.4
editor-stats, v0.17.0
file-icons, v1.5.7
filesize, v0.2.0
flex-tool-bar, v0.4.2
git-projects, v1.14.1
git-tab-status, v1.9.2
gutter-shadow, v0.5.0
highlight-selected, v0.9.3
keyboard-scroll, v0.4.0
keyboard-sounds, v0.2.0
language-dotenv, v1.0.0
language-fish-shell, v1.0.2
language-generic-config, v0.2.0
language-gitignore, v0.2.0
language-hosts, v0.1.2
language-slim, v0.4.0
minimap, v4.10.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.1
minimap-selection, v4.2.0
open-recent, v2.2.4
opened-files, v0.0.5
pigments, v0.6.0
read-only-indicator, v0.2.0
save-session, v0.15.5
symbols-tree-view, v0.9.3
tool-bar, v0.1.7
tool-bar-main, v0.0.8
tree-view-git-status, v0.1.1
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by paulpflug** [comment]
I'm unsure how you did that.. but I catched that error in 0.0.6

**Comment by aujkis** [comment]
After package installation, didn't even get the chance to modify config.

**Comment by paulpflug** [comment]
should be fixed, feel free to reply if I'm wrong

thanks for reporting :smile:
