### ISSUE TITLE
Uncaught TypeError: Cannot read property '__vue__' of null

### ISSUE THREAD

**Issue by lexicalunit** [paulpflug/opened-files#2]
[Enter steps to reproduce below:]
1. Open a bunch of files.
2. Start closing them using keyboard short cuts, one by one.

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [opened-files](https://github.com/paulpflug/opened-files) package, v0.0.10
### Stack Trace

Uncaught TypeError: Cannot read property '**vue**' of null

```
At /Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/directives/repeat.js:545

TypeError: Cannot read property '__vue__' of null
  at findNextVm (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/directives/repeat.js:545:22)
  at Directive.module.exports.diff (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/directives/repeat.js:314:25)
  at Directive.module.exports.update (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/directives/repeat.js:173:29)
  at Array.update._update (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/directive.js:74:17)
  at Watcher.p.run (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/watcher.js:173:15)
  at run (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/batcher.js:49:14)
  at Array.flush (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/batcher.js:34:3)
  at MutationObserver.handle (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/util/env.js:39:16)

```
### Commands

```
     -5:31.8.0 core:delete (atom-text-editor.editor.is-focused)
     -5:31.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -5:29.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:28.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -5:28.6.0 core:delete (atom-text-editor.editor.is-focused)
     -5:28.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:41.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:40.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:21.1.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:20.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -4:20.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -4:20.1.0 core:select-to-top (atom-text-editor.editor.is-focused)
     -4:19.8.0 core:delete (atom-text-editor.editor.is-focused)
     -4:19.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:21.4.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:18.7.0 core:close (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete",
      "exception-reporting",
      "autoflow",
      "autosave",
      "background-tips",
      "bookmarks",
      "encoding-selector",
      "language-toml",
      "metrics",
      "open-on-github",
      "snippets",
      "styleguide",
      "update-package-dependencies",
      "welcome",
      "linter-clang",
      "atom-pair",
      "rainbow-selection",
      "wrap-guide"
    ],
    "themes": [
      "isotope-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.4
autocomplete-plus-python-jedi, v0.3.6
column-select, v0.2.0
cursor-count, v0.2.0
event-watch, v3.7.7
file-icons, v1.5.7
git-tab-status, v1.9.2
highlight-selected, v0.9.3
isotope-ui, v2.4.0
language-applescript, v0.2.0
language-diff, v0.3.0
language-latex, v0.6.1
language-puppet, v0.12.0
language-rust, v0.4.3
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-erb, v0.1.1
linter-flake8, v1.4.2
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1
minimap, v4.10.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
monokai, v0.14.0
multi-wrap-guide, v0.17.0
opened-files, v0.0.10
python-isort, v0.0.7
python-yapf, v0.7.0
red-wavy-underline, v0.3.0
set-syntax, v0.3.0
soft-wrap-indicator, v0.7.0
symbols-tree-view, v0.9.3
tab-control, v0.6.2
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by paulpflug** [comment]
followup error of #3, I believe..

**Comment by lexicalunit** [comment]
I _think_ I actually got the error in #3 first, but... I'm not 100% on that. They did seem to happen at nearly the same time.
