### ISSUE TITLE
Uncaught TypeError: Cannot read property '$remove' of undefined

### ISSUE THREAD

**Issue by coling** [paulpflug/opened-files#29]
[Enter steps to reproduce below:]
1. Open several files in a tree view mode
2. Go to settings and switch back to list view

**Atom Version**: 1.8.0
**System**: "Mageia 5"
**Thrown From**: [opened-files](https://github.com/paulpflug/opened-files) package, v0.3.6
### Stack Trace

Uncaught TypeError: Cannot read property '$remove' of undefined

```
At ~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:12998

TypeError: Cannot read property '$remove' of undefined
    at Directive._teardown (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:12998:30)
    at teardownDirs (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:11455:13)
    at unlink (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:11434:5)
    at VueComponent._unlinkFn (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13082:7)
    at VueComponent.Vue._destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13198:12)
    at VueComponent.Vue.$destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13947:10)
    at VueComponent.Vue._destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13189:25)
    at VueComponent.Vue.$destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13947:10)
    at VueComponent.Vue._destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13189:25)
    at VueComponent.Vue.$destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13947:10)
    at VueComponent.Vue._destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13189:25)
    at VueComponent.Vue.$destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13947:10)
    at VueComponent.Vue._destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13189:25)
    at VueComponent.Vue.$destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13947:10)
    at VueComponent.Vue._destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13189:25)
    at VueComponent.Vue.$destroy (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:13947:10)
    at Fragment.beforeRemove (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:8496:22)
    at Fragment.multiRemove [as remove] (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:8470:8)
    at Directive.remove (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:8930:12)
    at Directive.diff (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:8751:14)
    at Directive.update (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:8657:10)
    at VueComponent._update (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:12803:15)
    at Watcher.run (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:7978:17)
    at runBatcherQueue (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:7706:13)
    at Array.flushBatcherQueue (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:7682:3)
    at MutationObserver.nextTickHandler (~/.atom/packages/opened-files/node_modules/vue/dist/vue.common.js:434:16)
```
### Commands

```
     -3:45.5.0 core:backspace (atom-text-editor#opened-files.mfpIdent.editor.mini.is-focused)
     -3:33.8.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "file-watcher"
    ],
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  },
  "opened-files": {
    "removeOnClose": true
  }
}
```
### Installed Packages

``` coffee
# User
chary-tree-view, v0.2.3
editorconfig, v1.4.1
foldername-tabs, v0.2.1
highlight-selected, v0.11.2
linter, v1.11.11
linter-php, v1.2.0
opened-files, v0.3.6
php-integrator-annotations, v0.4.1
php-integrator-autocomplete-plus, v0.8.1
php-integrator-base, v0.9.5
php-integrator-call-tips, v0.2.4
php-integrator-navigation, v0.7.1
php-integrator-symbol-viewer, v0.6.1
php-integrator-tooltips, v0.6.1

# Dev
No dev packages
```

**Comment by coling** [comment]
Note: It also just happened when I closed a file.

The option to remove the item from the tree is enabled in my settings.

**Comment by coling** [comment]
I've not really been using this for a while, so I'll just close it.
