### ISSUE TITLE
Uncaught TypeError: Cannot read property 'entry' of null

### ISSUE THREAD

**Issue by lexicalunit** [paulpflug/opened-files#3]
[Enter steps to reproduce below:]
1. Open a bunch of files.
2. Start closing them using keyboard short cuts, one by one.

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [opened-files](https://github.com/paulpflug/opened-files) package, v0.0.10
### Stack Trace

Uncaught TypeError: Cannot read property 'entry' of null

```
At /Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/instance/scope.js:92

TypeError: Cannot read property 'entry' of null
  at VueComponent.proxyGetter [as entry] (/Users/atroschinetz/.atom/packages/opened-files/node_modules/atom-vue-component-loader/node_modules/vue/src/instance/scope.js:92:24)
  at /Users/atroschinetz/.atom/packages/opened-files/components_compiled/file.js:161:35
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didDestroyPaneItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane-container.js:311:27)
  at Pane.module.exports.Pane.removeItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:386:17)
  at Pane.module.exports.Pane.destroyItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:442:16)
  at Pane.module.exports.Pane.destroyActiveItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:602:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace.js:641:21)
  at atom-workspace.atom.commands.add.core:close (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:314:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
  2x -6:23.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:23.5.0 core:select-down (atom-text-editor.editor.is-focused)
     -6:23.3.0 core:delete (atom-text-editor.editor.is-focused)
     -6:23.2.0 core:save (atom-text-editor.editor.is-focused)
     -5:36.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:35.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:15.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:15.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:15.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -5:14.8.0 core:select-to-top (atom-text-editor.editor.is-focused)
     -5:14.5.0 core:delete (atom-text-editor.editor.is-focused)
     -5:14.4.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:16.1.0 application:new-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  6x -1:13.4.0 core:close (atom-text-editor.editor.is-focused)
     -0:17.3.0 core:cancel (a.btn-issue.btn.btn-error)
 17x -0:16.8.0 core:close (a.btn-issue.btn.btn-error)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "autocomplete",
      "exception-reporting",
      "autoflow",
      "autosave",
      "background-tips",
      "bookmarks",
      "encoding-selector",
      "language-toml",
      "metrics",
      "open-on-github",
      "snippets",
      "styleguide",
      "update-package-dependencies",
      "welcome",
      "linter-clang",
      "atom-pair",
      "rainbow-selection",
      "wrap-guide"
    ],
    "themes": [
      "isotope-ui",
      "monokai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.4
autocomplete-plus-python-jedi, v0.3.6
column-select, v0.2.0
cursor-count, v0.2.0
event-watch, v3.7.7
file-icons, v1.5.7
git-tab-status, v1.9.2
highlight-selected, v0.9.3
isotope-ui, v2.4.0
language-applescript, v0.2.0
language-diff, v0.3.0
language-latex, v0.6.1
language-puppet, v0.12.0
language-rust, v0.4.3
linter, v0.12.7
linter-coffeelint, v0.3.2
linter-csslint, v0.0.13
linter-erb, v0.1.1
linter-flake8, v1.4.2
linter-puppet-lint, v0.2.9
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1
minimap, v4.10.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
monokai, v0.14.0
multi-wrap-guide, v0.17.0
opened-files, v0.0.10
python-isort, v0.0.7
python-yapf, v0.7.0
red-wavy-underline, v0.3.0
set-syntax, v0.3.0
soft-wrap-indicator, v0.7.0
symbols-tree-view, v0.9.3
tab-control, v0.6.2
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by paulpflug** [comment]
I think this was due to a race for closing the same tab from two different panes nearly simultaneously.
I added a catch for this.

Should work now, thanks for reporting :smile:

**Comment by paulpflug** [comment]
Oh.. you should be able to use cmd+alt+w to close all unpinned files..

**Comment by lexicalunit** [comment]
:+1:
